In [203]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier as dtc
from sklearn.tree import DecisionTreeRegressor as dtr
from sklearn import preprocessing 
import sklearn.model_selection as sk
from sklearn.metrics import accuracy_score 
from sklearn.model_selection import train_test_split

In [204]:
#retrieving dataset
df=pd.read_excel(r"D:\MAIL\oops.xlsx")

In [205]:
le=preprocessing.LabelEncoder()
year=le.fit_transform(df.YEAR)
year_map = dict(zip(le.classes_, le.transform(le.classes_)))
types=le.fit_transform(df['EXAM TYPE'])
types_map = dict(zip(le.classes_, le.transform(le.classes_)))
top=le.fit_transform(df.TOPICS)
top_map = dict(zip(le.classes_, le.transform(le.classes_)))
subtop=le.fit_transform(df.SUBTOPICS)
subtop_map = dict(zip(le.classes_, le.transform(le.classes_)))
marks=le.fit_transform(df.MARKS)
marks_map = dict(zip(le.classes_, le.transform(le.classes_)))
marks_map
year_map

{'2014-15': 0, '2016-17': 1, '2017-18': 2, '2018-19': 3}

In [206]:
independant=list(zip(year,subtop)) 
model1=dtc(criterion='entropy') 
xtest,xtrain,ytest,ytrain=sk.train_test_split(independant,marks,test_size=0.90,train_size=0.1,random_state=43)

In [207]:
model1.fit(np.array(xtrain).reshape(-1,2),np.array(ytrain).reshape(-1,1))

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [208]:
ypred=model1.predict(np.array(xtest).reshape(-1,2))
ypred

array([8, 0, 3, 7, 4, 5, 5, 4, 5, 7, 7, 3, 0, 3, 5, 5, 4, 4, 4, 3, 5, 0,
       4], dtype=int64)

In [209]:
score=accuracy_score(ytest,ypred)
score

0.21739130434782608

In [210]:
from sklearn.tree import export_graphviz as tree
tree(model1,out_file=r'D:\MAIL\DecisionTree1C.txt.dot')

In [211]:
#Now second model will predict the marks when we feed the year,examtype and subtopic into it
independant=list(zip(year,types,subtop))
model2=dtc(criterion='entropy') 
xtest,xtrain,ytest,ytrain=sk.train_test_split(independant,marks,test_size=0.75,train_size=0.25,random_state=43)

In [212]:
model2.fit(np.array(xtrain).reshape(-1,3),np.array(ytrain).reshape(-1,1))

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [213]:
ypred=model2.predict(np.array(xtest).reshape(-1,3))
ypred

array([8, 6, 9, 5, 5, 7, 5, 5, 5, 3, 7, 5, 7, 4, 5, 9, 4, 4, 5, 6, 4, 7,
       6, 5, 5, 4, 7, 5, 5, 5, 5, 7, 8, 7, 5, 7, 4, 7, 5, 5, 5, 7, 6, 4,
       7, 3, 2, 0, 5, 5, 4, 4, 4, 4, 5, 0, 8], dtype=int64)

In [214]:
from sklearn.tree import export_graphviz as tree
tree(model2,out_file=r'D:\MAIL\DecisionTree2C.txt.dot')

In [215]:
import sklearn.model_selection as sk
independant=list(zip(subtop)) 
model3=dtr() 
xtest,xtrain,ytest,ytrain=sk.train_test_split(independant,df["MARKS"],test_size=0.85,train_size=0.15,random_state=43)

In [216]:
model3.fit(np.array(xtrain).reshape(-1,1),np.array(ytrain).reshape(-1,1))

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')

In [217]:
ypred=model3.predict(np.array(xtest).reshape(-1,1))
ypred

array([7.5       , 7.27272727, 6.625     , 8.66666667, 6.        ,
       4.5       , 4.5       , 7.        , 7.5       , 6.4       ,
       8.66666667, 7.57142857, 6.        , 8.        , 7.36363636,
       6.        , 6.        , 6.        , 6.4       , 7.27272727,
       6.66666667, 7.36363636, 6.        , 5.45454545, 4.5       ,
       6.        , 6.        , 7.57142857, 5.45454545, 5.45454545,
       6.        , 6.66666667, 4.        , 6.        ])

In [218]:
from sklearn.metrics import mean_squared_error as mse, r2_score 

In [219]:
accuracy=r2_score(ytest,ypred)
print(mse(ytest,ypred))
print(accuracy)

3.0760586386758564
0.1927528294417049


In [220]:
from sklearn.tree import export_graphviz as tree
tree(model2,out_file=r'D:\MAIL\DecisionTree1R.txt.dot')

In [221]:
#Now second model will predict the marks when we feed the year, topic into it
independant=list(zip(year,top,subtop))
model4=dtr() 
xtest,xtrain,ytest,ytrain=sk.train_test_split(independant,df["MARKS"],test_size=0.85,train_size=0.15,random_state=43)

In [222]:
model4.fit(np.array(xtrain).reshape(-1,3),np.array(ytrain).reshape(-1,1))

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')

In [223]:
ypred=model4.predict(np.array(xtest).reshape(-1,3))
ypred

array([ 6.75      ,  5.        ,  6.        ,  8.        ,  6.        ,
        6.        ,  4.        ,  5.        ,  6.        , 10.        ,
        8.        , 10.        ,  4.        ,  7.        ,  7.25      ,
        5.        ,  6.        ,  6.        ,  3.        ,  6.66666667,
        8.        ,  8.        ,  6.        ,  3.33333333,  4.5       ,
        6.        ,  8.        ,  6.33333333,  5.        ,  5.        ,
        5.        ,  6.        ,  4.        , 10.        ])

In [224]:
from sklearn.metrics import mean_squared_error as mse, r2_score 

In [225]:
accuracy=r2_score(ytest,ypred)
print(mse(ytest,ypred))
print(accuracy)

5.530637254901961
-0.4513999243284148


In [226]:
from sklearn.tree import export_graphviz as tree
tree(model4,out_file=r'D:\MAIL\DecisionTree2R.txt.dot')